tumavideo/yop

package-lock.json
package.json
src/components/Opportunity.js
src/pages/_app.tsx
src/pages/index.tsx
src/pages/jobs/[id].tsx
src/styles/theme.css
yarn.lock

...and remove any React GA artifacts
**Testing**
Check the Vercel dashboard for integration once deployed.

Add Vercel Analytics

---

src/pages/index.tsx

**Changes**
- Optimize the code by reducing the number of requests and fetching the data in parallel
- This allows you to make multiple requests concurrently, which can lead to faster execution
**Testing**
- Go to the main page and ensure that it loads
- Compare the load performance between local and zr.com (both pull from the same source but one should be faster than the other)

Optimize Initial Request

---

app/layout.tsx
app/page.tsx
components/Carousel.js

Carousel margin top and bottom updated
Set body background to white

Margin and background updated

---

app/page.tsx
components/CTA.tsx
components/Hero.js

**Changes**
- Add CTA for company
- Update copy for hero
**Testing**
Observe changes on homepage

Company CTA

---

components/layout/Footer.js

**Changes**
* Point subscription form/button to Tally
**Testing**
* Click the subscribe button in the footer and enter your email on the next page.
* If you need to see how it looks in the backend, reach out for a screenshot or creds.

Fix Subscriptions

---

app/community/page.tsx
app/opportunity/page.tsx
components/Nothing.js

**Changes**
- Hide functionality if not logged in
- Limit opportunities to 6 if not logged in
- Update "Nothing" component copy and presentation
- Remove unused filter logic
**Testing**
1. Go to the opportunity and community pages
2. Observe that there is a call to action prompting for sign up if the user wants to see more

Limit Logged Out Functionality

---

app/register/page.tsx
app/register/register-form.tsx

**Changes**
- Add government select option (yes / no)
- Conditionally show dropdown if registering as company
**Testing**
Using any of the CTAs for companies observe that there is no a drop down to select if the registrant is government.

Govt Registration Check

---

app/page.tsx

Carousel has been moved to the top.

HomePgae Banner

---

app/styles/globals.css

**Changes**
Remove background and font color for body/html
**Testing**
See if problems still persist.

Fix body background and text color

---

app/community/page.tsx
app/services/page.tsx
components/layout/Header.tsx

Service page added
Extra item Menu navigation
Component Arrangement

Services page and navigation

---

components/Carousel.js

**Changes**
Position the carousel buttons outside of the banners

Carousel Button Shift

---

app/about/page.tsx
components/Hero.js

**Changes**
Update copy for the following:
- About page: about and why sections
- Update subtext on home hero component

Update Website Nomenclature

---

app/layout.tsx
app/opportunity/page.tsx
components/Filters.js
lib/queries.js
utils/index.ts

**Changes**
- Get fields from API
- Add field to query params to filter results

Fix Filter

---

app/register/page.tsx
app/services/page.tsx
components/Filters.js

**Changes**
Center registration form and remove background.

Center Registration Form

---

components/Filters.js

**Changes**
Set to job if category is null.

Fix Filter Application Error

---

app/opportunity/[id]/apply-now.tsx
app/opportunity/[id]/fail-modal.tsx
app/opportunity/[id]/page.tsx
app/opportunity/[id]/thanks-modal.tsx
app/profile/page.tsx
app/profile/update-profile-form.tsx
package.json
utils/index.ts

**Changes**
* Upload resume
* Apply button
* Thanks and redirect modals
* Version bump NextJS

User Profile

---

app/account/update-password/page.tsx
app/login/forgot-password/page.tsx
app/login/page.tsx
app/register/register-form.tsx

**Changes**
- Change one month trial to join now
- Change name to first name and last name
**Testing**
Observe the following...
First name + Last name on sign up
No remember me or forgot password
Join now on every other page

Update Auth Page Nomenclature

---

app/profile/page.tsx
components/Nothing.js

**Changes**
Change CTA text - nothing complicated

Change Text on Services Page (Not Signed In)

---

components/layout/Footer.js

**Changes**
I hope this is the final decision.

chore: change footer text

---

components/CTA.tsx

**Changes**
chore: change more words
**Note:** Should we put these pieces of text on Sanity?

More CTA Changes

---

components/layout/Header.tsx

chore: change menu wording

---

app/community/page.tsx
components/CTA.tsx

chore: update wording on CTA on community page

---

app/login/login-form.tsx

- The user is forwarded to the previous page after sign in
- Visiting the site from an external link sends you to the homepage after signup
- Also applied the button styling to the sign out button 
<a href="https://gyazo.com/1097e862eba40d82c4c5532d6c4b068b"><img src="https://i.gyazo.com/1097e862eba40d82c4c5532d6c4b068b.gif" alt="Image from Gyazo" width="600"/></a>
<a href="https://gyazo.com/768eaa71029d638c3d1801276eb6d6db"><img src="https://i.gyazo.com/768eaa71029d638c3d1801276eb6d6db.gif" alt="Image from Gyazo" width="600"/></a>

fix: forward to the referrer after sign in

---

app/page.tsx
components/Collage.js
components/Hero.js

- Created the Collage component
- Reduced the amount of images to only 2
- The collage is `hidden `on `md` an `sm` breakpoints
- Removed the `sm` and `md` breakpoints since the collage is `hidden` 
<a href="https://gyazo.com/711855769362cfb5b6770be9db5b5cd3"><img src="https://i.gyazo.com/711855769362cfb5b6770be9db5b5cd3.jpg" alt="Image from Gyazo" width="400"/></a>
<a href="https://gyazo.com/8ad0ea3125c08682b3302226667107e5"><img src="https://i.gyazo.com/8ad0ea3125c08682b3302226667107e5.png" alt="Image from Gyazo" width="400"/></a>

feat: Modified the Collage component

---

app/profile/page.tsx
app/profile/update-profile-form.tsx

- Added null checks for 'user' object
<a href="https://gyazo.com/e3fed780f6d475e7fd4e6b1ec18e735b"><img src="https://i.gyazo.com/e3fed780f6d475e7fd4e6b1ec18e735b.gif" alt="Image from Gyazo" width="700"/></a>

fix: resolve to an empty object when destructuring```null```

---

seo/index.ts

<a href="https://gyazo.com/c6ff4f2930c3773bdc2ba2d35d337543"><img src="https://i.gyazo.com/c6ff4f2930c3773bdc2ba2d35d337543.png" alt="Image from Gyazo" width="566.4"/></a>
<a href="https://gyazo.com/e8b2262116e50b334d6101ec23a947e8"><img src="https://i.gyazo.com/e8b2262116e50b334d6101ec23a947e8.png" alt="Image from Gyazo" width="589.6"/></a>

fix: fixed the missing items to meet the googlebot requirements

---

app/opportunity/[id]/apply-now.tsx
app/opportunity/[id]/fail-modal.tsx
app/opportunity/[id]/page.tsx

**Changes**
- Modify apply button to take links
- Modify modal to show different messages
**Testing**
Try applying for 3 different jobs
**Edge case**: You can click the link three times if you find the job three times but the likelihood of that happening is low.

Limit Apply Button

---

app/opportunity/[id]/apply-now.tsx
app/profile/page.tsx
app/profile/referral-section.tsx
app/profile/update-profile-form.tsx
app/register/register-form.tsx
lib/database.types.ts
package.json
tsconfig.json
utils/toast.js
yarn.lock

- Used supabase to create the referral after the user signs up
- Appended the Referral component on the profile page to allow the user to copy to clipboard
- Created a simple toast element in the utils/toast that shows up when the link is clicked

feat: Create the referral on sign up

---

app/layout.tsx
app/loading.tsx
app/opportunity/[id]/apply-now.tsx
app/profile/referral-section.tsx
app/profile/update-profile-form.tsx
app/styles/animations.css
utils/toast.js

- Added a count on the referrals table to get the number of referred users per account
- Added a Folder icon for small screens
- Users can upload resumes by name
- Placeholder icon to represent file uploaded
- Removed emojis in place for the 💡
- Limited the uploads to 3 resumes
- Added a loader for the upload and deletion of the current upload
- Added a toast for the successful uploads and submissions
- Handle errors via refresh
- Resumes were null during form submission -> fixed that

feat: Added logic to apply to users with 3 or referrals

---

app/profile/update-profile-form.tsx

fix: changed the display name function

---

components/layout/Footer.js

remove mobile number

---

app/ReferralModalTrigger.tsx
app/opportunity/[id]/page.tsx
app/page.tsx
app/profile/referral-section.tsx
app/profile/upload-resume.tsx
app/styles/globals.css
components/Opportunity.js
components/ReferralModalTrigger.tsx
components/layout/Footer.js
package.json
public/index.html

- Created a modal trigger to initiate the giveaway process

feat: Add Referral flow to engage users to participate into the giveaway

---

app/login/google-login-button.tsx
app/login/page.tsx
app/profile/referral-section.tsx
tailwind.config.js

- Users will now be able to login to their existing accounts using the one time sign in
- Created the login by google button
- Implemented the the social auth on the login page
- changed the copy on the referral section

feat: added the social logins

---

app/page.tsx

chore: make Xmas image responsive

---

app/opportunity/page.tsx
lib/queries.js

**Changes**
- Extend the job listings to all jobs that are none-expired
- Rejigged the magic numbers to be more realistic with what we have on the platform
- Show an "end of feed" notification
**Test**
All above

feat: show an end of feed notification

---

app/login/login-form.tsx
app/register/register-form.tsx

chore: simplify technical language

---

components/Feature.js

chore: limit image size on smaller screens

---

app/profile/update-profile-form.tsx

chore: prevent the icon from shrinking

---

app/auth/callback/route.ts
app/login/google-login-button.tsx
app/login/page.tsx
app/register/page.tsx
app/register/register-form.tsx
lib/database.types.ts
package.json

**Changes Made**
- Added logic to store the referral and provider cookies on the signup page.
- Implemented code to retrieve the stored cookies on the auth/callback route.
- Updated the social login functionality to use the retrieved referral code during the registration process.

Fix for Social Login Not Using Referral Code

---

app/page.tsx
components/Xmas.tsx
components/XmasPoster.tsx
package-lock.json

**Changes**
- change the xmas banner and poster into components
- remove them from the body of the landing page
**Testing**
Make sure nothing is broken on the home page
**Dev Note**
Xmas component can be used as follows: `<Xmas session={session} data={data} user={user} />`

Remove Xmas Special

---

components/Feature.js
components/XmasPoster.tsx

fix: Cleared the abolute line on the app

---

app/login/google-login-button.tsx
app/onboarding/onboarding-form.tsx
app/onboarding/page.tsx
app/profile/referral-section.tsx
app/profile/update-profile-form.tsx
app/profile/upload-resume.tsx
app/styles/globals.css
middleware.ts

- Created a new page `onboarding` that uses the onboarding form with only two steps
- Step 1: Upload resume
- Step 2: Share referral code
- Overridden the upload resume to dynamically change the size of the container
- Added the `.background-animate` selector that create a swipe animation for skeletons

feat: 144-145 Created the onboarding multistep that prompts resume uploading for first time users

---

app/page.tsx

chore: change CTA wording

---

app/profile/update-profile-form.tsx

chore: limit number of downloadable resumes

---

app/opportunity/page.tsx
components/ScrollToTop.css
components/ScrollToTop.js

* decided it should be blue to stand out
* shows up when you start to scroll down
* visible on both mobile and desktop

feat: scroll to top

---

app/common/alert-modal.tsx
app/login/login-form.tsx
app/login/page.tsx
app/onboarding/page.tsx
app/profile/delete-modal.tsx
app/profile/update-profile-form.tsx

* add two modals, alert and delete
* handle logic on login if deleted
* handle delete on the profile page

feat: delete account
